language: python
# with next we get on container based infrastructure, this enables caching
sudo: false
python:
  - 2.7.6
cache:
  pip: true
  directories:
    - $HOME/buildout-cache

before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - virtualenv .
  - bin/pip install --upgrade pip setuptools zc.buildout

install:
  - bin/buildout -N -t 20 -c buildout.cfg

script:
  - bin/code-analysis
  - bin/coverage run bin/test

after_success:
  - pip install -q coveralls python-coveralls==2.5.0
  - coveralls
